### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by asteph7cd** [mastershef/information_retrieval#3]
il file di output dallo script di reperimento dovrebbe essere estensione .treceval affichè si possa fare la valutazione suppongo sia .run tanto per dargli un nome

**Comment by 0x090909** [comment]
modifica pure allora

**Comment by asteph7cd** [comment]
posso fare rinomina?

**Comment by 0x090909** [comment]
yess, ma alla fine e' indifferente l'estensione che usi, tanto il contenuto e' lo stesso

**Comment by 0x090909** [comment]
a sto punto modifica anche il readme

**Comment by asteph7cd** [comment]
hai provato se funziona comunque usando il programma?
pensavo richiedesse che il file avesse .treceval

**Comment by asteph7cd** [comment]
nvm

**Comment by 0x090909** [comment]
non ancora, devo configurarmi treceval
